#!/usr/bin/python
from __future__ import print_function
import sys, re, bz2
dump = {0:[], 1:[], 2:[], 3:[], 4:[], 5:[], 6:[], 7:[], 8:[]}
def printItems(prevQuery, query, kind):
	global dump
	if prevQuery is None:
		dump[kind].append(str(query) + ' ')
	elif int(query) - int(prevQuery) != 0:
		dump[kind].append(str(int(query) - int(prevQuery)) + ' ')
	elif int(query) - int(prevQuery) == 0:
		dump[kind].append(',')
	return int(query)
def readFile(file):
	days = ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
	months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	tz = ['EDT', 'EST']
	data = ""
	items = {"prevNum": None, "prevDayWeek": None, "prevMonth": None, "prevDay": None, "prevHour": None, "prevMin": None, "prevSec": None, "prevTZ": None, "prevYear": None}
	with open(file) as f:
		for line in f:
			curLine = re.split(r'\s+|:', line)
			items["prevNum"] = printItems(items["prevNum"], curLine[0].replace(",", ""), 0)
			items["prevDayWeek"] = printItems(items["prevDayWeek"], days.index(curLine[1]), 1)
			items["prevMonth"] = printItems(items["prevMonth"], months.index(curLine[2]), 2)
			items["prevDay"] = printItems(items["prevDay"], curLine[3], 3)
			items["prevHour"] = printItems(items["prevHour"], curLine[4], 4)
			items["prevMin"] = printItems(items["prevMin"], curLine[5], 5)
			items["prevSec"] = printItems(items["prevSec"], curLine[6], 6)
			items["prevTZ"] = printItems(items["prevTZ"], tz.index(curLine[7]), 7)
			items["prevYear"] = printItems(items["prevYear"], curLine[8], 8)
		for i in range(9):
			string = "".join(dump[i])
			data = data + string + ';'
		compressed = bz2.compress(data)
		print(compressed)
def main():
	readFile(sys.argv[1])
main()